### PR TITLE
RAD-270 Extract frequently used code into js file

### PR DESCRIPTION
**Pull request by Schwasrz94**
## Description

* add jasmine to test js code
* add radiology.js
* add tests for radiology.js
* modify jsp files to use extracted code
* add radiology.js to includeScripts.jsp

## Related Issue

see https://issues.openmrs.org/browse/RAD-270

### CODE REVIEW

**Comment by dkayiwa** [comment]
@Schwasrz94 @teleivo did you see this? https://ci.openmrs.org/browse/RAD-RM-282

**Comment by teleivo** [comment]
@dkayiwa yes thanks you! We will look into it

**Comment by teleivo** [comment]
@dkayiwa should be fixed with https://github.com/openmrs/openmrs-module-radiology/commit/34f49d04a75ef37c15374273041bee11fa48ddd4

**Comment by dkayiwa** [comment]
@teleivo yey!!! 👍

**Pull request merged**
