### PR TITLE
RAD-387 Add sourcemaps for more comfortable frontend development

### PR DESCRIPTION
**Pull request by durac**
## Description

- add development maven profile to omod pom.xml
- add dev-task and tasks with creation of sourcemaps of js and css files
  to gulpfile.js
## Related Issue

see https://issues.openmrs.org/browse/RAD-387

### CODE REVIEW

**Comment by dkayiwa** [comment]
@teleivo @ivange94 do you wanna review this? :)

**Comment by ivange94** [comment]
@teleivo will probably be the one to review this. I only review pull requests that have something to do with MRRT :)

**Comment by dkayiwa** [comment]
@teleivo do you think this is ready for merging? :)

**Comment by dkayiwa** [comment]
@teleivo do you have any comments on this? :)

**Pull request merged**
