### PR TITLE
RAD-59 Update module to run on Platform 2.0

### PR DESCRIPTION
**Pull request by teleivo**
## Description
* upgrade openmrs dependency to 2.0-SNAPSHOT
* compile with java8
* add dependency in omod to legacyui since openmrs-core doesnt contain ui
anymore
* travis ci build only on java8
* update readme
* org.openmrs.util.HibernateEnumType was deleted, switch to hibernates enum type in mapping xml's
* add dependency on legacyui to omod
* dependencies of emrapi should have scope test

## Related Issue

see https://issues.openmrs.org/browse/RAD-59

### CODE REVIEW

**Comment by dkayiwa** [comment]
@teleivo did you intentionally decide not to support platform versions before 2.0? :)

**Comment by teleivo** [comment]
@dkayiwa yes

**Comment by dkayiwa** [comment]
@teleivo this pull request still hangs and has failing tests. You need to do the following:
1) Add in these changes: https://github.com/openmrs/openmrs-module-radiology/commit/879be8d1dbfb96525e9b625e11eab31ef7daccdc
2) Remove check_digit="false" from the four test datasets at https://github.com/openmrs/openmrs-module-radiology/tree/master/api/src/test/resources/org/openmrs/module/radiology/include
3) Fix RadiologyOrderTest.isDiscontinuationAllowed_shouldReturnTrueIfRadiologyOrderIsActiveNotInProgressAndNotCompleted()

On another note, you have lots of @Autowired for services, which greatly slows down the running of unit tests. Hopefully you saw this https://issues.openmrs.org/browse/TRUNK-3806 and how it led to this commit https://github.com/PIH/openmrs-module-emr/pull/1/commits/6578e308eb6683e2eaecca8559785a82d1372403

**Comment by teleivo** [comment]
@dkayiwa thanks a lot for your awesome help!! full steam ahead into the 2.0 future :+1:

**Comment by dkayiwa** [comment]
@teleivo thanks too for being the first module developer to make your module 2.x compliant!!! :)
I would like to encourage many more module developers to do just like you. 👍

**Pull request merged**
