### PR TITLE
RAD-165 Include tinymce as report editor

### PR DESCRIPTION
**Pull request by oliverkrakora**
Integration of the tinymce texteditor for the report.

see https://issues.openmrs.org/browse/RAD-165

### CODE REVIEW

**Comment by teleivo** [comment]
please rebase on latest master and merge into one single commit

**Comment by teleivo** [comment]
Can you just do something like
```bash
git reset --soft HEAD~NrOfYourCommitsTillMaster
git commit -m 'new commit message'
```

**Comment by oliverkrakora** [comment]
Now it worked, i tried squashing the commits by rebasing them but I always ran into merge conflicts.
Thank you!

**Comment by teleivo** [comment]
Try 'gut pull rebase NameOfRemoteBranch master'
And if that doesn work just create a fresh branch from latest master and cherry pick your commit. Or copy paste your changes like in the old days. You shouldn't have to many changes in this commit anyway

**Comment by teleivo** [comment]
PS always look at your diff. This tells you that you still havent gotten a clean single commit

**Comment by teleivo** [comment]
icons dont show on firefox/chrome.

**Pull request closed without merging**
